package com.demo.entities;
// Generated Jun 4, 2020 2:35:22 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "nvl", uniqueConstraints = @UniqueConstraint(columnNames = "orderId"))
public class Payment implements java.io.Serializable {

	private Integer id;
	private Order order;
	private Double price;
	private String method;
	private String paypalCustomer;
	private Double paypalGross;
	private Double paypalFee;
	private Boolean status;
	private Date createdDate;
	private Date modifiedDate;

	public Payment() {
	}

	public Payment(Order order, Date createdDate, Date modifiedDate) {
		this.order = order;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
	}

	public Payment(Order order, Double price, String method, String paypalCustomer, Double paypalGross,
			Double paypalFee, Boolean status, Date createdDate, Date modifiedDate) {
		this.order = order;
		this.price = price;
		this.method = method;
		this.paypalCustomer = paypalCustomer;
		this.paypalGross = paypalGross;
		this.paypalFee = paypalFee;
		this.status = status;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderId", unique = true, nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "method", length = 100)
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "paypalCustomer", length = 250)
	public String getPaypalCustomer() {
		return this.paypalCustomer;
	}

	public void setPaypalCustomer(String paypalCustomer) {
		this.paypalCustomer = paypalCustomer;
	}

	@Column(name = "paypalGross", precision = 22, scale = 0)
	public Double getPaypalGross() {
		return this.paypalGross;
	}

	public void setPaypalGross(Double paypalGross) {
		this.paypalGross = paypalGross;
	}

	@Column(name = "paypalFee", precision = 22, scale = 0)
	public Double getPaypalFee() {
		return this.paypalFee;
	}

	public void setPaypalFee(Double paypalFee) {
		this.paypalFee = paypalFee;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdDate", nullable = false, insertable = false, updatable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedDate", nullable = false, insertable = false, updatable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
