package com.demo.entities;
// Generated Jun 4, 2020 2:35:22 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PromotionDetailId generated by hbm2java
 */
@Embeddable
public class PromotionDetailId implements java.io.Serializable {

	private int promotionId;
	private int productId;

	public PromotionDetailId() {
	}

	public PromotionDetailId(int promotionId, int productId) {
		this.promotionId = promotionId;
		this.productId = productId;
	}

	@Column(name = "promotionId", nullable = false)
	public int getPromotionId() {
		return this.promotionId;
	}

	public void setPromotionId(int promotionId) {
		this.promotionId = promotionId;
	}

	@Column(name = "productId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PromotionDetailId))
			return false;
		PromotionDetailId castOther = (PromotionDetailId) other;

		return (this.getPromotionId() == castOther.getPromotionId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPromotionId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
