package com.demo.entities;
// Generated Jun 4, 2020 2:35:22 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PromotionDetail generated by hbm2java
 */
@Entity
@Table(name = "promotion_detail", catalog = "nvl")
public class PromotionDetail implements java.io.Serializable {

	private PromotionDetailId id;
	private Product product;
	private Promotion promotion;
	private boolean status;

	public PromotionDetail() {
	}

	public PromotionDetail(PromotionDetailId id, Product product, Promotion promotion, boolean status) {
		this.id = id;
		this.product = product;
		this.promotion = promotion;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "promotionId", column = @Column(name = "promotionId", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)) })
	public PromotionDetailId getId() {
		return this.id;
	}

	public void setId(PromotionDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotionId", nullable = false, insertable = false, updatable = false)
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
